-- CRIA UM BANCO DE DADOS
CREATE DATABASE Teste;

-- USA UM BANCO DE DADOS
USE Teste;

-- CRIA UMA TABELA
CREATE TABLE Funcionarios
(
   IdFuncionario INT PRIMARY KEY IDENTITY,
   Nome VARCHAR(100)
)

CREATE TABLE Empresas
(
    IdEmpresa INT PRIMARY KEY IDENTITY,
	IdFuncionario INT FOREIGN KEY REFERENCES Funcionarios (IdFuncionario),
	NomeEmpresa VARCHAR(100)
)

-- ALTERA A TABELA
ALTER TABLE Funcionarios
-- EXCLUI A COLUNA SELECIONADA
DROP COLUMN Nome;

-- EXCLUI UMA TABELA
DROP TABLE Funcionarios;
-- EXCLUI UM BANCO DE DADOS
DROP DATABASE Teste;
