CREATE DATABASE Exercicio_1_3

CREATE TABLE Clinica
(
   IdClinica INT PRIMARY KEY IDENTITY,
   Endereco VARCHAR(100)
)

CREATE TABLE Dono
(
   IdDono INT PRIMARY KEY IDENTITY,
   Nome VARCHAR(50) NOT NULL
)

CREATE TABLE TipoPet
(
   IdTipoPet INT PRIMARY KEY IDENTITY,
   Descricao VARCHAR(100) NOT NULL
)

CREATE TABLE Raca
(
   IdRaca INT PRIMARY KEY IDENTITY,
   Descricao VARCHAR(100) NOT NULL
)

